/**
 * eagle-bridge-fixtures.integration.test.js
 *
 * Real-file integration tests for the eagle_bridge deterministic tracing path.
 * Uses actual PNG/WebP/JPEG images generated by the eagle-metadata-bridge ComfyUI
 * custom node to verify the full binary-extraction → parsing → tag/annotation pipeline.
 *
 * Fixture files: tests/fixtures/bridge-*.{png,webp,jpg}
 *
 * To add a new fixture:
 *   1. Generate an image via ComfyUI with eagle-metadata-bridge node
 *   2. Copy the PNG/WebP to tests/fixtures/bridge-<name>.{png,webp}
 *   3. Add a test case to TEST_CASES below (with expected tags/annotation)
 */
import { describe, it, expect, beforeAll } from 'vitest';
import { readFileSync, existsSync } from 'fs';
import { join } from 'path';
import { createRequire } from 'module';

const require = createRequire(import.meta.url);
const MetadataService = require('../../js/metadata-parser/integration/MetadataService.js');
const TagGenerator = require('../../js/metadata-processor/TagGenerator.js');
const AnnotationBuilder = require('../../js/metadata-processor/AnnotationBuilder.js');

const ROOT = process.cwd();

function readFixture(relativePath) {
  const full = join(ROOT, relativePath);
  if (!existsSync(full)) return null;
  return new Uint8Array(readFileSync(full));
}

// All options enabled
const ALL_SETTINGS = {
  checkpoint: true, lora: true, positive: true, negative: true,
  seed: true, steps: true, cfg: true, sampler: true, scheduler: true,
  includeAllSamplers: false,
};

function t(key) {
  const map = {
    'ui.option.checkpoint': 'Checkpoint', 'ui.option.lora': 'LoRA',
    'ui.option.seed': 'Seed', 'ui.option.steps': 'Steps', 'ui.option.sampler': 'Sampler',
  };
  return map[key] || key.split('.').pop();
}

// ---------------------------------------------------------------------------
// Test cases – expected tags (sorted) and annotation are hand-written ground truth
// ---------------------------------------------------------------------------
const TEST_CASES = [
  {
    name: 'bridge-simple',
    label: 'single KSampler, novaAnimeXL',
    fixtures: [
      { file: 'tests/fixtures/bridge-simple.png',  mimeType: 'image/png'  },
      { file: 'tests/fixtures/bridge-simple.webp', mimeType: 'image/webp' },
      { file: 'tests/fixtures/bridge-simple.jpg',  mimeType: 'image/jpeg' },
    ],
    expectedTags: [
      '1girl', 'casual blouse', 'cfg:8.00', 'masterpiece',
      'neg:worst quality', 'novaanimexl_ilv150',
      'sampler:dpmpp_2m', 'seed:1111111', 'steps:30',
    ],
    expectedAnnotation: [
      '[Generation Info]',
      'Checkpoint: novaAnimeXL_ilV150',
      'LoRA: ',
      '',
      '[Base Sampler - KSampler (ID: 18)]',
      'Checkpoint: novaAnimeXL_ilV150',
      'Seed: 1111111',
      'Steps: 30 | CFG: 8.0 | Sampler: dpmpp_2m | Scheduler: simple',
      'Positive: masterpiece, 1girl,  casual blouse',
      'Negative: worst quality,',
    ].join('\n'),
  },
  {
    name: 'bridge-multi',
    label: '2x KSampler, novaAnimeXL',
    fixtures: [
      { file: 'tests/fixtures/bridge-multi.png',  mimeType: 'image/png'  },
      { file: 'tests/fixtures/bridge-multi.webp', mimeType: 'image/webp' },
      { file: 'tests/fixtures/bridge-multi.jpg',  mimeType: 'image/jpeg' },
    ],
    expectedTags: [
      '1girl', 'basque beret', 'cfg:8.00', 'masterpiece',
      'neg:bad hands', 'neg:worst quality', 'novaanimexl_ilv140',
      'sampler:euler_ancestral', 'seed:1111111', 'steps:30', 'ultra-detailed',
    ],
    expectedAnnotation: [
      '[Generation Info]',
      'Checkpoint: novaAnimeXL_ilV140',
      'LoRA: ',
      '',
      '[Base Sampler - KSampler (ID: 18)]',
      'Seed: 1111111',
      'Steps: 30 | CFG: 8.0 | Sampler: euler_ancestral | Scheduler: simple',
      'Positive: masterpiece, 1girl, basque beret,',
      'Negative: worst quality,',
      '',
      '[Step 2 - KSampler (ID: 28)]',
      'Seed: 222222',
      'Steps: 20 | CFG: 7.0 | Sampler: euler_ancestral | Scheduler: normal',
      'Positive: (ultra-detailed),',
      'Negative: bad hands',
    ].join('\n'),
  },
  {
    name: 'bridge-conditioning-combine',
    label: 'ImpactCombineConditionings, novaAnimeXL',
    fixtures: [
      { file: 'tests/fixtures/bridge-conditioning-combine.png',  mimeType: 'image/png'  },
      { file: 'tests/fixtures/bridge-conditioning-combine.webp', mimeType: 'image/webp' },
      { file: 'tests/fixtures/bridge-conditioning-combine.jpg',  mimeType: 'image/jpeg' },
    ],
    expectedTags: [
      '1girl', 'cfg:8.00', 'masterpiece',
      'neg:bad hands', 'neg:bad quality', 'neg:extra limbs', 'neg:worst quality',
      'novaanimexl_ilv140', 'sampler:dpmpp_2m', 'seed:1111111', 'steps:30',
      'stick pants', 'tailored jacket',
    ],
    expectedAnnotation: [
      '[Generation Info]',
      'Checkpoint: novaAnimeXL_ilV140',
      'LoRA: ',
      '',
      '[Base Sampler - KSampler (ID: 18)]',
      'Checkpoint: novaAnimeXL_ilV140',
      'Seed: 1111111',
      'Steps: 30 | CFG: 8.0 | Sampler: dpmpp_2m | Scheduler: simple',
      'Positive: masterpiece,, 1girl,, tailored jacket,stick pants',
      'Negative: worst quality,, bad quality,, bad hands, extra limbs,',
    ].join('\n'),
  },
  {
    name: 'bridge-lora-simple',
    label: 'LoraLoader single, novaAnimeXL',
    fixtures: [
      { file: 'tests/fixtures/bridge-lora-simple.png',  mimeType: 'image/png'  },
      { file: 'tests/fixtures/bridge-lora-simple.webp', mimeType: 'image/webp' },
      { file: 'tests/fixtures/bridge-lora-simple.jpg',  mimeType: 'image/jpeg' },
    ],
    expectedTags: [
      '1girl', 'basque beret', 'cfg:8.00', 'hime cut_xl_illustrious_v1.0',
      'himecut', 'masterpiece', 'neg:bad hands', 'neg:worst quality',
      'novaanimexl_ilv140', 'pink hair color',
      'sampler:euler_ancestral', 'seed:1111111', 'steps:30', 'ultra-detailed',
    ],
    expectedAnnotation: [
      '[Generation Info]',
      'Checkpoint: novaAnimeXL_ilV140',
      'LoRA: hime cut_XL_illustrious_V1.0',
      '',
      '[Base Sampler - KSampler (ID: 18)]',
      'Seed: 1111111',
      'Steps: 30 | CFG: 8.0 | Sampler: euler_ancestral | Scheduler: simple',
      'Positive: masterpiece, 1girl, basque beret, himecut, pink hair color',
      'Negative: worst quality,',
      '',
      '[Step 2 - KSampler (ID: 28)]',
      'Seed: 222222',
      'Steps: 20 | CFG: 7.0 | Sampler: euler_ancestral | Scheduler: normal',
      'Positive: (ultra-detailed),',
      'Negative: bad hands',
    ].join('\n'),
  },
  {
    name: 'bridge-lora-stack',
    label: 'LoraLoaderStack rgthree, novaAnimeXL',
    fixtures: [
      { file: 'tests/fixtures/bridge-lora-stack.png',  mimeType: 'image/png'  },
      { file: 'tests/fixtures/bridge-lora-stack.webp', mimeType: 'image/webp' },
      { file: 'tests/fixtures/bridge-lora-stack.jpg',  mimeType: 'image/jpeg' },
    ],
    expectedTags: [
      '1girl', 'basque beret', 'brown hair color', 'cfg:8.00',
      'half twintail_illustrious_v1.0', 'masterpiece',
      'neg:bad hands', 'neg:worst quality', 'novaanimexl_ilv140',
      'sampler:euler_ancestral', 'seed:1111111', 'steps:30', 'twintail', 'ultra-detailed',
    ],
    expectedAnnotation: [
      '[Generation Info]',
      'Checkpoint: novaAnimeXL_ilV140',
      'LoRA: half twintail_illustrious_V1.0',
      '',
      '[Base Sampler - KSampler (ID: 18)]',
      'Seed: 1111111',
      'Steps: 30 | CFG: 8.0 | Sampler: euler_ancestral | Scheduler: simple',
      'Positive: masterpiece, 1girl, basque beret, twintail, brown hair color',
      'Negative: worst quality,',
      '',
      '[Step 2 - KSampler (ID: 28)]',
      'Seed: 222222',
      'Steps: 20 | CFG: 7.0 | Sampler: euler_ancestral | Scheduler: normal',
      'Positive: (ultra-detailed),',
      'Negative: bad hands',
    ].join('\n'),
  },
  {
    name: 'bridge-i2i',
    label: 'DetailerForEachDebug (ADetailer), novaAnimeXL',
    fixtures: [
      { file: 'tests/fixtures/bridge-i2i.png',  mimeType: 'image/png'  },
      { file: 'tests/fixtures/bridge-i2i.webp', mimeType: 'image/webp' },
      { file: 'tests/fixtures/bridge-i2i.jpg',  mimeType: 'image/jpeg' },
    ],
    expectedTags: [
      'cfg:8.00', 'masterpiece', 'neg:worst quality', 'novaanimexl_ilv150',
      'red color casual blouse', 'sampler:dpmpp_2m', 'seed:1111111',
      'silver color hair', 'steps:20',
    ],
    expectedAnnotation: [
      '[Generation Info]',
      'Checkpoint: novaAnimeXL_ilV150',
      'LoRA: ',
      '',
      '[Base Sampler - DetailerForEachDebug (ID: 36)]',
      'Checkpoint: novaAnimeXL_ilV150',
      'Seed: 1111111',
      'Steps: 20 | CFG: 8.0 | Sampler: dpmpp_2m | Scheduler: simple',
      'Positive: masterpiece,  red color casual blouse, silver color hair',
      'Negative: worst quality,',
    ].join('\n'),
  },
];

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------
describe('eagle_bridge real-fixture integration tests', () => {
  let service;

  beforeAll(() => {
    service = new MetadataService();
  });

  TEST_CASES.forEach(({ name, label, fixtures, expectedTags, expectedAnnotation }) => {
    fixtures.forEach(({ file, mimeType }) => {
      const fmt = mimeType.split('/')[1].toUpperCase();
      describe(`${name} (${label}) ${fmt}`, () => {

        it('fixture file exists', () => {
          expect(existsSync(join(ROOT, file))).toBe(true);
        });

        it('eagle_bridge chunk is present in fixture', () => {
          const buffer = readFixture(file);
          if (!buffer) return;
          const results = service.extractMetadata(buffer, mimeType);
          const comfy = results.find(r => r.format === 'comfyui');
          expect(comfy).toBeDefined();
          expect(comfy.sampler_fallback).toBe(false);
        });

        it('extracts comfyui format without error', () => {
          const buffer = readFixture(file);
          if (!buffer) return;
          expect(() => service.extractMetadata(buffer, mimeType)).not.toThrow();
          const results = service.extractMetadata(buffer, mimeType);
          expect(results.find(r => r.format === 'comfyui')).toBeDefined();
        });

        it('has at least one generation step', () => {
          const buffer = readFixture(file);
          if (!buffer) return;
          const results = service.extractMetadata(buffer, mimeType);
          const comfy = results.find(r => r.format === 'comfyui');
          expect(comfy?.generationSteps?.length).toBeGreaterThan(0);
        });

        it('deterministic mode: is not sampler_fallback', () => {
          const buffer = readFixture(file);
          if (!buffer) return;
          const results = service.extractMetadata(buffer, mimeType);
          const comfy = results.find(r => r.format === 'comfyui');
          expect(comfy?.sampler_fallback).toBe(false);
        });

        it('tags match expected', () => {
          const buffer = readFixture(file);
          if (!buffer) return;
          const results = service.extractMetadata(buffer, mimeType);
          const comfy = results.find(r => r.format === 'comfyui');
          if (!comfy) return;
          const { tags } = TagGenerator.generate(comfy, ALL_SETTINGS);
          expect([...tags].sort()).toEqual(expectedTags);
        });

        it('annotation matches expected', () => {
          const buffer = readFixture(file);
          if (!buffer) return;
          const results = service.extractMetadata(buffer, mimeType);
          const comfy = results.find(r => r.format === 'comfyui');
          if (!comfy) return;
          const annotation = AnnotationBuilder.build(comfy, ALL_SETTINGS, t);
          expect(annotation).toBe(expectedAnnotation);
        });
      });
    });
  });
});
