/**
 * eagle-bridge-fixtures.integration.test.js
 *
 * Real-file integration tests for the eagle_bridge deterministic tracing path.
 * Uses actual PNG images generated by the eagle-metadata-bridge ComfyUI custom node
 * (not synthetic test data) to verify the full binary-extraction → parsing pipeline.
 *
 * Fixture files: tests/fixtures/bridge-*.png
 * Expected JSON: tests/expected/bridge-*.json
 *
 * To add a new fixture:
 *   1. Generate an image via ComfyUI with eagle-metadata-bridge node
 *   2. Copy the PNG to tests/fixtures/bridge-<name>.png
 *   3. Run: node scripts/analyze-image.js tests/fixtures/bridge-<name>.png
 *   4. Create tests/expected/bridge-<name>.json with the expected values
 *   5. Add a test case to the TEST_CASES array below
 */
import { describe, it, expect, beforeAll } from 'vitest';
import { readFileSync, existsSync } from 'fs';
import { join } from 'path';
import { createRequire } from 'module';

const require = createRequire(import.meta.url);
const MetadataService = require('../../js/metadata-parser/integration/MetadataService.js');

const ROOT = process.cwd();

function readFixture(relativePath) {
  const full = join(ROOT, relativePath);
  if (!existsSync(full)) return null;
  return new Uint8Array(readFileSync(full));
}

function readExpected(relativePath) {
  const full = join(ROOT, relativePath);
  if (!existsSync(full)) return null;
  return JSON.parse(readFileSync(full, 'utf-8'));
}

// ---------------------------------------------------------------------------
// Test cases – add new bridge-*.png fixtures here
// ---------------------------------------------------------------------------
const TEST_CASES = [
  {
    name: 'bridge-simple (single KSampler, novaAnimeXL) PNG',
    fixture: 'tests/fixtures/bridge-simple.png',
    expected: 'tests/expected/bridge-simple.json',
    mimeType: 'image/png',
  },
  {
    name: 'bridge-simple (single KSampler, novaAnimeXL) WebP',
    fixture: 'tests/fixtures/bridge-simple.webp',
    expected: 'tests/expected/bridge-simple.json',
    mimeType: 'image/webp',
  },
  {
    name: 'bridge-multi (2x KSampler, hassakuXL) PNG',
    fixture: 'tests/fixtures/bridge-multi.png',
    expected: 'tests/expected/bridge-multi.json',
    mimeType: 'image/png',
  },
  {
    name: 'bridge-multi (2x KSampler, hassakuXL) WebP',
    fixture: 'tests/fixtures/bridge-multi.webp',
    expected: 'tests/expected/bridge-multi.json',
    mimeType: 'image/webp',
  },
  {
    name: 'bridge-conditioning-combine (ImpactCombineConditionings, boleromix) PNG',
    fixture: 'tests/fixtures/bridge-conditioning-combine.png',
    expected: 'tests/expected/bridge-conditioning-combine.json',
    mimeType: 'image/png',
  },
  {
    name: 'bridge-conditioning-combine (ImpactCombineConditionings, boleromix) WebP',
    fixture: 'tests/fixtures/bridge-conditioning-combine.webp',
    expected: 'tests/expected/bridge-conditioning-combine.json',
    mimeType: 'image/webp',
  },
  {
    name: 'bridge-lora-simple (LoraLoader single, novaAnimeXL) PNG',
    fixture: 'tests/fixtures/bridge-lora-simple.png',
    expected: 'tests/expected/bridge-lora-simple.json',
    mimeType: 'image/png',
  },
  {
    name: 'bridge-lora-simple (LoraLoader single, novaAnimeXL) WebP',
    fixture: 'tests/fixtures/bridge-lora-simple.webp',
    expected: 'tests/expected/bridge-lora-simple.json',
    mimeType: 'image/webp',
  },
  {
    name: 'bridge-lora-stack (LoraLoaderStack rgthree, novaAnimeXL) PNG',
    fixture: 'tests/fixtures/bridge-lora-stack.png',
    expected: 'tests/expected/bridge-lora-stack.json',
    mimeType: 'image/png',
  },
  {
    name: 'bridge-lora-stack (LoraLoaderStack rgthree, novaAnimeXL) WebP',
    fixture: 'tests/fixtures/bridge-lora-stack.webp',
    expected: 'tests/expected/bridge-lora-stack.json',
    mimeType: 'image/webp',
  },
  // JPEG variants
  {
    name: 'bridge-simple (single KSampler, novaAnimeXL) JPEG',
    fixture: 'tests/fixtures/bridge-simple.jpg',
    expected: 'tests/expected/bridge-simple.json',
    mimeType: 'image/jpeg',
  },
  {
    name: 'bridge-multi (2x KSampler, hassakuXL) JPEG',
    fixture: 'tests/fixtures/bridge-multi.jpg',
    expected: 'tests/expected/bridge-multi.json',
    mimeType: 'image/jpeg',
  },
  {
    name: 'bridge-conditioning-combine (ImpactCombineConditionings, boleromix) JPEG',
    fixture: 'tests/fixtures/bridge-conditioning-combine.jpg',
    expected: 'tests/expected/bridge-conditioning-combine.json',
    mimeType: 'image/jpeg',
  },
  {
    name: 'bridge-lora-simple (LoraLoader single, novaAnimeXL) JPEG',
    fixture: 'tests/fixtures/bridge-lora-simple.jpg',
    expected: 'tests/expected/bridge-lora-simple.json',
    mimeType: 'image/jpeg',
  },
  {
    name: 'bridge-lora-stack (LoraLoaderStack rgthree, novaAnimeXL) JPEG',
    fixture: 'tests/fixtures/bridge-lora-stack.jpg',
    expected: 'tests/expected/bridge-lora-stack.json',
    mimeType: 'image/jpeg',
  },
  // bridge-i2i (image-to-image + ADetailer, novaAnimeXL) – PNG / WebP / JPEG
  {
    name: 'bridge-i2i (DetailerForEachDebug, novaAnimeXL) PNG',
    fixture: 'tests/fixtures/bridge-i2i.png',
    expected: 'tests/expected/bridge-i2i.json',
    mimeType: 'image/png',
  },
  {
    name: 'bridge-i2i (DetailerForEachDebug, novaAnimeXL) WebP',
    fixture: 'tests/fixtures/bridge-i2i.webp',
    expected: 'tests/expected/bridge-i2i.json',
    mimeType: 'image/webp',
  },
  {
    name: 'bridge-i2i (DetailerForEachDebug, novaAnimeXL) JPEG',
    fixture: 'tests/fixtures/bridge-i2i.jpg',
    expected: 'tests/expected/bridge-i2i.json',
    mimeType: 'image/jpeg',
  },
];

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------
describe('eagle_bridge real-fixture integration tests', () => {
  let service;

  beforeAll(() => {
    service = new MetadataService();
  });

  TEST_CASES.forEach(({ name, fixture, expected: expectedPath, mimeType }) => {
    describe(name, () => {
      it('fixture file exists', () => {
        expect(existsSync(join(ROOT, fixture))).toBe(true);
      });

      it('eagle_bridge chunk is present in fixture', () => {
        const buffer = readFixture(fixture);
        if (!buffer) return;
        const results = service.extractMetadata(buffer, mimeType);
        const comfy = results.find(r => r.format === 'comfyui');
        expect(comfy).toBeDefined();
        expect(comfy.sampler_fallback).toBe(false);
      });

      it('extracts comfyui format without error', () => {
        const buffer = readFixture(fixture);
        if (!buffer) return;
        expect(() => service.extractMetadata(buffer, mimeType)).not.toThrow();
        const results = service.extractMetadata(buffer, mimeType);
        const comfy = results.find(r => r.format === 'comfyui');
        expect(comfy).toBeDefined();
      });

      it('matches expected metadata snapshot', () => {
        const buffer = readFixture(fixture);
        const expected = readExpected(expectedPath);
        if (!buffer || !expected) return;

        const results = service.extractMetadata(buffer, mimeType);
        const comfy = results.find(r => r.format === 'comfyui');
        expect(comfy).toBeDefined();
        expect(comfy).toMatchObject(expected);
      });

      it('has at least one generation step', () => {
        const buffer = readFixture(fixture);
        if (!buffer) return;
        const results = service.extractMetadata(buffer, mimeType);
        const comfy = results.find(r => r.format === 'comfyui');
        expect(comfy?.generationSteps?.length).toBeGreaterThan(0);
      });

      it('deterministic mode: is not sampler_fallback', () => {
        const buffer = readFixture(fixture);
        if (!buffer) return;
        const results = service.extractMetadata(buffer, mimeType);
        const comfy = results.find(r => r.format === 'comfyui');
        expect(comfy?.sampler_fallback).toBe(false);
      });
    });
  });
});
