/**
 * eagle-bridge-fixtures.integration.test.js
 *
 * Real-file integration tests for the eagle_bridge deterministic tracing path.
 * Uses actual PNG images generated by the eagle-metadata-bridge ComfyUI custom node
 * (not synthetic test data) to verify the full binary-extraction → parsing pipeline.
 *
 * Fixture files: tests/fixtures/bridge-*.png
 * Expected JSON: tests/expected/bridge-*.json
 *
 * To add a new fixture:
 *   1. Generate an image via ComfyUI with eagle-metadata-bridge node
 *   2. Copy the PNG to tests/fixtures/bridge-<name>.png
 *   3. Run: node scripts/analyze-image.js tests/fixtures/bridge-<name>.png
 *   4. Create tests/expected/bridge-<name>.json with the expected values
 *   5. Add a test case to the TEST_CASES array below
 */
import { describe, it, expect, beforeAll } from 'vitest';
import { readFileSync, existsSync } from 'fs';
import { join } from 'path';
import { createRequire } from 'module';

const require = createRequire(import.meta.url);
const MetadataService = require('../../js/metadata-parser/integration/MetadataService.js');

const ROOT = process.cwd();

function readFixture(relativePath) {
  const full = join(ROOT, relativePath);
  if (!existsSync(full)) return null;
  return new Uint8Array(readFileSync(full));
}

function readExpected(relativePath) {
  const full = join(ROOT, relativePath);
  if (!existsSync(full)) return null;
  return JSON.parse(readFileSync(full, 'utf-8'));
}

// ---------------------------------------------------------------------------
// Test cases – add new bridge-*.png fixtures here
// ---------------------------------------------------------------------------
const TEST_CASES = [
  {
    name: 'bridge-simple (single KSampler, novaAnimeXL) PNG',
    fixture: 'tests/fixtures/bridge-simple.png',
    expected: 'tests/expected/bridge-simple.json',
    mimeType: 'image/png',
    checkFields: ['format', 'checkpoint', 'seed', 'steps', 'cfg', 'sampler', 'scheduler', 'sampler_fallback', 'eagle_bridge']
  },
  {
    name: 'bridge-simple (single KSampler, novaAnimeXL) WebP',
    fixture: 'tests/fixtures/bridge-simple.webp',
    expected: 'tests/expected/bridge-simple.json',
    mimeType: 'image/webp',
    checkFields: ['format', 'checkpoint', 'seed', 'steps', 'cfg', 'sampler', 'scheduler', 'sampler_fallback', 'eagle_bridge']
  },
  {
    name: 'bridge-multi (2x KSampler, hassakuXL) PNG',
    fixture: 'tests/fixtures/bridge-multi.png',
    expected: 'tests/expected/bridge-multi.json',
    mimeType: 'image/png',
    checkFields: ['format', 'checkpoint', 'seed', 'steps', 'cfg', 'sampler', 'scheduler', 'sampler_fallback', 'eagle_bridge']
  },
  {
    name: 'bridge-multi (2x KSampler, hassakuXL) WebP',
    fixture: 'tests/fixtures/bridge-multi.webp',
    expected: 'tests/expected/bridge-multi.json',
    mimeType: 'image/webp',
    checkFields: ['format', 'checkpoint', 'seed', 'steps', 'cfg', 'sampler', 'scheduler', 'sampler_fallback', 'eagle_bridge']
  },
  {
    name: 'bridge-conditioning-combine (ImpactCombineConditionings, boleromix) PNG',
    fixture: 'tests/fixtures/bridge-conditioning-combine.png',
    expected: 'tests/expected/bridge-conditioning-combine.json',
    mimeType: 'image/png',
    checkFields: ['format', 'checkpoint', 'seed', 'steps', 'cfg', 'sampler', 'scheduler', 'sampler_fallback', 'eagle_bridge'],
    checkBasePositiveContains: 'tailored jacket'
  },
  {
    name: 'bridge-conditioning-combine (ImpactCombineConditionings, boleromix) WebP',
    fixture: 'tests/fixtures/bridge-conditioning-combine.webp',
    expected: 'tests/expected/bridge-conditioning-combine.json',
    mimeType: 'image/webp',
    checkFields: ['format', 'checkpoint', 'seed', 'steps', 'cfg', 'sampler', 'scheduler', 'sampler_fallback', 'eagle_bridge'],
    checkBasePositiveContains: 'tailored jacket'
  }
];

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------
describe('eagle_bridge real-fixture integration tests', () => {
  let service;

  beforeAll(() => {
    service = new MetadataService();
  });

  TEST_CASES.forEach(({ name, fixture, expected: expectedPath, mimeType, checkFields, checkLoras, checkBasePositiveContains }) => {
    describe(name, () => {
      it('fixture file exists', () => {
        expect(existsSync(join(ROOT, fixture))).toBe(true);
      });

      it('eagle_bridge chunk is present in fixture', () => {
        // Verify the fixture actually contains eagle_bridge metadata
        // (if it doesn't, this fixture is not testing the right thing)
        const buffer = readFixture(fixture);
        if (!buffer) return;
        // We can't directly read tEXt chunks here, but we can verify
        // the parse result shows eagle_bridge was detected (sampler_fallback = false
        // and a result was extracted from the correct node)
        const results = service.extractMetadata(buffer, mimeType);
        const comfy = results.find(r => r.format === 'comfyui');
        expect(comfy).toBeDefined();
        expect(comfy.sampler_fallback).toBe(false);
      });

      it('extracts comfyui format without error', () => {
        const buffer = readFixture(fixture);
        if (!buffer) return;
        expect(() => service.extractMetadata(buffer, mimeType)).not.toThrow();
        const results = service.extractMetadata(buffer, mimeType);
        const comfy = results.find(r => r.format === 'comfyui');
        expect(comfy).toBeDefined();
      });

      it('matches expected metadata snapshot', () => {
        const buffer = readFixture(fixture);
        const expected = readExpected(expectedPath);
        if (!buffer || !expected) return;

        const results = service.extractMetadata(buffer, mimeType);
        const comfy = results.find(r => r.format === 'comfyui');
        expect(comfy).toBeDefined();

        for (const field of checkFields) {
          if (field === 'eagle_bridge') continue; // checked separately below
          if (expected[field] !== undefined) {
            expect(comfy[field], `field: ${field}`).toBe(expected[field]);
          }
        }
      });

      it('eagle_bridge.final_node_id matches expected', () => {
        const buffer = readFixture(fixture);
        const expected = readExpected(expectedPath);
        if (!buffer || !expected?.eagle_bridge) return;
        const results = service.extractMetadata(buffer, mimeType);
        const comfy = results.find(r => r.format === 'comfyui');
        expect(comfy?.eagle_bridge?.final_node_id, 'eagle_bridge.final_node_id')
          .toBe(expected.eagle_bridge.final_node_id);
      });

      it('has at least one generation step', () => {
        const buffer = readFixture(fixture);
        if (!buffer) return;
        const results = service.extractMetadata(buffer, mimeType);
        const comfy = results.find(r => r.format === 'comfyui');
        expect(comfy?.generationSteps?.length).toBeGreaterThan(0);
      });

      it('deterministic mode: is not sampler_fallback', () => {
        const buffer = readFixture(fixture);
        if (!buffer) return;
        const results = service.extractMetadata(buffer, mimeType);
        const comfy = results.find(r => r.format === 'comfyui');
        expect(comfy?.sampler_fallback).toBe(false);
      });

      if (checkLoras) {
        it('base sampler ancestor scan finds expected LoRAs', () => {
          const buffer = readFixture(fixture);
          if (!buffer) return;
          const results = service.extractMetadata(buffer, mimeType);
          const comfy = results.find(r => r.format === 'comfyui');
          expect(comfy?.loras).toBeDefined();
          for (const lora of checkLoras) {
            expect(comfy.loras, `expected lora: ${lora}`).toContain(lora);
          }
        });
      }

      if (checkBasePositiveContains) {
        it('base sampler positive text contains expected string (ConditioningCombine)', () => {
          const buffer = readFixture(fixture);
          if (!buffer) return;
          const results = service.extractMetadata(buffer, mimeType);
          const comfy = results.find(r => r.format === 'comfyui');
          const base = comfy?.generationSteps?.find(s => s.isBase);
          expect(base?.positive).toContain(checkBasePositiveContains);
        });
      }
    });
  });
});
